apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base

components:
  - ./../../components/security/tls_auto+sasl_plain
  - ./../../components/deployment/single-node
  - ./../../components/monitoring/prometheus-grafana

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ca-pair-sslcerts # seems that cfk is expecting this name to autogenerate
    type: "kubernetes.io/tls"
    files:
      - ./assets/tls/tls.crt
      - ./assets/tls/tls.key
