apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base

components:
  - ./../../components/security/tls-generated
  - ./../../components/security/authn-sasl-plain
  - ./../../components/security/authz-acl
  - ./../../components/deployment/single-node
