apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - zookeeper.yml
  - kafka.yml
  - schemaregistry.yml
  - controlcenter.yml

secretGenerator:
  - name: ca-pair-sslcerts # seems that cfk is expecting this name to autogenerate
    options:
      disableNameSuffixHash: true
    files:
      - tls.crt=ca.pem
      - tls.key=ca-key.pem
    type: "kubernetes.io/tls"
