apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: kafka-credentials
  options:
    disableNameSuffixHash: true
  files:
    - digest.txt
    - digest-users.json
    - plain.txt
    - plain-users.json
- name: controlcenter-credentials
  options:
    disableNameSuffixHash: true
  files:
    - plain.txt=controlcenter-plain.txt

patchesStrategicMerge:
  - zookeeper.yml
  - kafka.yml
  - controlcenter.yml
