apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  authorization:
    type: rbac
    superUsers:
    - User:devkafka
  services:
    mds:
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
      provider:
        type: ldap
        ldap:
          address: ldap://ldap.openldap.svc.cluster.local:389
          authentication:
            type: simple
            simple:
              secretRef: ldap-credential
          configurations:
            groupSearchBase: dc=test,dc=com
            groupObjectClass: group
            groupNameAttribute: cn
            groupMemberAttribute: member
            groupMemberAttributePattern: CN=(.*),DC=test,DC=com

            userSearchBase: dc=test,dc=com
            userObjectClass: organizationalRole
            userNameAttribute: cn
            #userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client

