apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: mds-token
    options:
      disableNameSuffixHash: true
    files:
      - mdsTokenKeyPair.pem
      - mdsPublicKey.pem

  - name: ldap-credential
    options:
      disableNameSuffixHash: true
    files:
      - ldap.txt

  - name: sr-mds-client
    options:
      disableNameSuffixHash: true
    literals:
      - |
        bearer.txt=username=devsr
        password=sr-secret

  - name: c3-mds-client
    options:
      disableNameSuffixHash: true
    literals:
      - |
        bearer.txt=username=devc3
        password=c3-secret
  
  - name: mds-client
    options:
      disableNameSuffixHash: true
    literals:
      - |
        bearer.txt=username=devkafka
        password=kafka-secret
  
  - name: rest-credential
    options:
      disableNameSuffixHash: true
    literals:
      - |
        bearer.txt=username=devkafka
        password=kafka-secret
      - |
        basic.txt=username=devkafka
        password=kafka-secret

patchesStrategicMerge:
  - kafka.yml
  - schemaregistry.yml
  - controlcenter.yml

resources:
  - kafkarest.yml

