apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: telemetry
    options:
      disableNameSuffixHash: true
    files:
      - telemetry.txt

patchesStrategicMerge:
  - zookeeper.yml
  - kafka.yml
  - controlcenter.yml
