apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.1.0
    init: confluentinc/confluent-init-container:2.3.0
  dataVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    probe:
      # how long to wait for c3 ui getting ready
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
    # disabling kubernetes security for container exec
    podSecurityContext: {}
