apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.1.0
    init: confluentinc/confluent-init-container:2.3.1
  podTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    podSecurityContext: {}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
