apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: kafka-client-config
    options:
      disableNameSuffixHash: true
    files:
      - kafka.properties

resources:
  - perf.yml
