apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../deployment/single-node

patchesStrategicMerge:
  - zookeeper.yml
  - kafka.yml
  - controlcenter.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ca-pair-sslcerts # seems that cfk is expecting this name to autogenerate
    files:
      - tls.crt=ca.pem
      - tls.key=ca-key.pem
    type: "kubernetes.io/tls"
